### ISSUE TITLE
Display note history in sidebar

### ISSUE THREAD

**Issue by Yukaii** [hackmdio/vscode-hackmd#15]
We now have a [CodiMD CLI](https://github.com/hackmdio/codimd-cli). While the HackMD API client is under development, we can now utilize existing [CodiMD's API implementation](https://github.com/hackmdio/codimd-cli/blob/master/src/api.ts) to implement a Tree view for note history.

### Tasks

- [ ] Copy CodiMD API client to project for now(since it's not published as npm package yet)
- [ ] Display note history as a tree in the sidebar
- [ ] Click on tree node should open the note content in the editor
- [ ] We can have more **inline actions** for note node like **preview**, **split-view**, or **edit mode**
    - GitLens' UI can be used for reference here
    - ![Screen Shot 2020-04-15 at 11 32 30 AM](https://user-images.githubusercontent.com/4230968/79296043-dbab6780-7f0c-11ea-8b57-4e51a9e110d6.png)

**Comment by Yukaii** [comment]
done in #18
